OrdererOrgs:
  - Name: Orderer
    Domain: poc
    Specs:
      - Hostname: orderer
#change the template count for increasing the number of peers for all the orgs
PeerOrgs:
  - Name: Org1
    Domain: org1
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org3
    Domain: org3
    Template:
      Count: 2
    Users:
      Count: 1
